[package]
name = "paper-specs"
version = "0.1.0"
entrypoint = "paper-specs.typ"
authors = ["Tobias WÃ¶lfel"]
license = "MIT"
description = "Collection of device specifications for page setup."
repository = "https://github.com/towoe/paper-specs"
keywords = ["devices", "paper", "remarkable", "epaper", "apple"]
categories = ["layout", "office"]
